# Generated by Django 2.1.5 on 2024-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
